### ISSUE TITLE
Data download

### ISSUE THREAD

**Issue by renderit** [datacamp/course-resources-ml-with-experts-budgets#1]
Hey, it seems the competition has ended hence I'm unable to download the dataset from the datadriven website. Is it possible for you to share the data somehow? i'd really like to try out the notebook! Any temporary link/dropbox anything works.. :)

**Comment by wsurles** [comment]
Its under 'Data Download' on the right menu. Under leaderboard.  Yeah, it took me a bit to find it too. 
Here is a direct link. 
https://www.drivendata.org/competitions/46/box-plots-for-education-reboot/data/
